version: '3.7'

services:
  wordpress:
    restart: always
    image: whatwewant/wordpress:${SERVICE_WORDPRESS_IMAGE_VERSION}
    ports:
      - 0.0.0.0:${SERVICE_WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${SERVICE_WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ${SERVICE_DATA}/wordpress:/var/www/html
    depends_on:
      - wordpress_db

  wordpress_db:
    restart: always
    image: whatwewant/mysql:${SERVICE_WORDPRESS_IMAGE_MYSQL_VERSION}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${SERVICE_WORDPRESS_DB_PASSWORD}
      MYSQL_DATABASE: wordpress
    # fix:
    #   mbind: Operation not permitted
    # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - ${SERVICE_DATA}/mysql:/var/lib/mysql

networks:
  default:
    external: true
    name: compose-ingress
